add tooltip
js-tasks-ru/htmlcss-20230530_julnbul pull request #10
Opened 2023-06-15 09:06 UTC by Julnbul

2023-06-15 09:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 20:18 UTC, GSemikozov requested changes

2023-06-15 20:18 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.wrapper {
вспомогательный блок? в файле стилей блока .tooltip не может быть никаких других блоков, кроме данного. если нужен враппер на странице с решением - то его можно оформить прямо в теге style на хтмл странице

2023-06-16 11:44 UTC, Julnbul commented on 05-lection3/01-tooltip/tooltip.css
> +.wrapper {
Исправила.

2023-06-16 20:54 UTC, GSemikozov approved these changes

2023-06-16 20:54 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-06-16 20:54 UTC, GSemikozov approved these changes

2023-06-16 20:54 UTC, merged