Mobile card prewiew
js-tasks-ru/htmlcss-20230530_julnbul pull request #14
Opened 2023-06-19 17:20 UTC by Julnbul

2023-06-19 17:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-19 21:06 UTC, GSemikozov requested changes

2023-06-19 21:06 UTC, GSemikozov commented on components/header/header.css
> +  .header__head-right {
очень плохо в классах вот так жестко привязывать положение) а если вдруг сделаем reverse на мобиле? тогда придется класс переписывать? или он будет обманывать разработчика?) в общем, я бы советовал более универсальное имя дать, например .header__col если это подойдет

2023-06-20 07:09 UTC, Julnbul commented on components/header/header.css
> +  .header__head-right {
поняла, спасибо) исправила

2023-06-20 07:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-20 09:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-20 12:55 UTC, GSemikozov requested changes

2023-06-20 12:55 UTC, GSemikozov commented on components/header/header.css
> +.header__head_page-component {
если есть какой-то опциональный элемент - то лучше на его уровни прописывать марджины (и тогда не придется обнулять)

2023-06-20 12:55 UTC, GSemikozov commented on components/header/header.css
> +  .header__head_page-component {
и - выше уже ведь обнуляли)

2023-06-20 13:12 UTC, Julnbul commented on components/header/header.css
> +.header__head_page-component {
исправила

2023-06-21 09:22 UTC, GSemikozov approved these changes

2023-06-21 09:22 UTC, merged