Input
js-tasks-ru/htmlcss-20230530_julnbul pull request #22
Opened 2023-06-27 14:40 UTC by Julnbul

2023-06-27 17:21 UTC, GSemikozov requested changes

2023-06-27 17:21 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input__block-input>input {
не стоит, лучше просто класс по БЭМ

2023-06-27 17:21 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  display: inline-block;
наверно абсолютом в нужном месте + по умолчанию скрыта?

2023-06-27 17:21 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input__block-input>input:focus {
см выше

2023-06-28 01:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-28 01:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-28 02:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-28 02:13 UTC, Julnbul commented on 07-lection5/04-input/input.css
> +.text-input__block-input>input {
исправила

2023-06-28 02:13 UTC, Julnbul commented on 07-lection5/04-input/input.css
> +.text-input__block-input>input:focus {
исправила

2023-06-28 02:15 UTC, Julnbul commented on 07-lection5/04-input/input.css
> +  display: inline-block;
не уверена, что поняла правильно механизм дальнейшего применения. исправила так, как поняла. надеюсь правильно)

2023-06-30 21:09 UTC, GSemikozov requested changes

2023-06-30 21:09 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input__block-input>input::placeholder {
просто text-input__input::placeholder

2023-06-30 21:09 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-input_success>.text-input__block-input>.text-input__icon,
не любую иконку, а именно .text-input__icon_success и тд (поскольку обе иконки сразу присутствуют в разметке)

2023-07-01 03:44 UTC, Julnbul commented on 07-lection5/04-input/input.css
> +.text-input_success>.text-input__block-input>.text-input__icon,
Исправила. Вопрос для понимания. Учитывая, что указан блок расположения иконки через модификатор .text-input_success или  .text-input_error,  код срабатывал правильно. Данное замечание касается читабельности кода? В смысле лучше добавить модификатор, чем городить длинные цепочки?

2023-07-01 10:31 UTC, GSemikozov approved these changes

2023-07-01 10:31 UTC, merged