add burger
js-tasks-ru/htmlcss-20230530_julnbul pull request #24
Opened 2023-06-28 11:57 UTC by Julnbul

2023-06-28 11:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-30 21:15 UTC, GSemikozov requested changes

2023-06-30 21:15 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.preload * {
всякие такие глобальные штуки описываем в глобальных файлах по типу main.css, и конечно же точно не в компонентах)

2023-06-30 21:15 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open {
это не часть блока .burger-menu

2023-06-30 21:15 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-icon {
.burger-menu__icon

2023-06-30 21:15 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__theme {
переключалку лучше позже реализовать как отдельный блок, так что в этом ПР добавлять не надо

2023-06-30 21:15 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar-menu__card_burger-menu {
лучше через классы-миксы внутри burger-menu

2023-07-04 11:51 UTC, Julnbul commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open {
не понимаю как здесь нужно реализовать. кнопка вызова бургер-меню должна быть частью блока .burger-menu? или нет?  как правильно? создать отдельную страницу для кнопки?

2023-07-04 11:53 UTC, Julnbul commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-icon {
здесь тоже не понимаю. предполагала, что кнопка отдельно от блока burger-menu, соответственно её класс не является элементом блока burger-menu.

2023-07-04 12:01 UTC, Julnbul commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__theme {
убрала

2023-07-04 12:22 UTC, Julnbul commented on components/sidebar/sidebar.css
> +.sidebar-menu__card_burger-menu {
здесь тоже не поняла. если речь о .sidebar-menu__card, то эти значения не для бургера, а для сайдбара на странице компонента. А если речь о .sidebar-menu__card_burger-menu, то там паддинги задаются, а не внешняя геометрия и позиционированиею

2023-07-05 21:18 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-open {
есть блок бургер-меню, а есть элемент который вызывает это меню, и таким элементом может быть все что угодно: иконка в хедере, текст в сайдбаре, кнопка в футере и так далее. Так что - надо удалить стили связанные с .burger-menu-open

2023-07-05 21:20 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu-icon {
здесь тоже все очень просто - блок называется .burger-menu, все остальное - его элементы и модификаторы, то есть содержать в названии своего класса тот блок, которому принадлежат: .burger-menu__icon - элемент icon принадлежит блоку burger-menu. А если пишем .burger-menu-icon - то это означает "блок с названием `.burger-menu-icon`"

2023-07-05 21:24 UTC, GSemikozov requested changes

2023-07-05 21:24 UTC, GSemikozov commented on components/sidebar/sidebar.css
> +.sidebar-menu__card_burger-menu {
.sidebar-menu__card_burger-menu - это специфический модификатор элемента блока .sidebar-menu, который задает паддинг другому блоку, то есть меняет его внутреннюю реализацию. Так делать нельзя. Как вариант - создаем класс элемента .sidebar-menu__burger-menu и ему задаем margin-top, либо тогда надо создавать модификатор в самом блоке .burger-menu

2023-07-06 12:45 UTC, Julnbul commented on components/sidebar/sidebar.css
> +.sidebar-menu__card_burger-menu {
здесь у меня видимо проблемы с пониманием логики БЭМ, связанные с изучением БЭМ по ютубу) Это было до курса, но путаница в голове ещё сохраняется. Изменила структуру. Пока остаются сомнения элемент или модификатор.

2023-07-26 13:15 UTC, closed without merging