add page
js-tasks-ru/htmlcss-20230530_julnbul pull request #4
Opened 2023-06-07 10:11 UTC by Julnbul

2023-06-07 10:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-07 21:11 UTC, GSemikozov requested changes

2023-06-07 21:11 UTC, GSemikozov commented on components/footer/footer.css
> +  width: 640px;
max-width

2023-06-09 14:13 UTC, GSemikozov approved these changes

2023-06-09 14:13 UTC, merged