add card-preview
js-tasks-ru/htmlcss-20230530_julnbul pull request #7
Opened 2023-06-09 19:17 UTC by Julnbul

2023-06-09 19:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-11 20:02 UTC, GSemikozov requested changes

2023-06-11 20:02 UTC, GSemikozov commented on components/main/main.css
> +.preview__list {
если мы здесь описываем блок main, то собственно класс блока мы уже определили, все остальное - лишь его элементы.
то есть .preview__list -> main__list, .preview-card -> .main__card и так длее.

2023-06-11 20:02 UTC, GSemikozov commented on components/main/main.css
> +.preview-card {
карточка - это все-таки отдельный блок

2023-06-11 20:02 UTC, GSemikozov commented on index.html
> +          <ul class="preview__list">
через список реализовывать не стоит

2023-06-11 20:02 UTC, GSemikozov commented on index.html
> +              <article class="preview-card">
это тег `<a>`

2023-06-12 04:28 UTC, Julnbul commented on components/main/main.css
> +.preview-card {
Отдельный блок- это значит, что оставить блоком, а не переписывать элементом блока main? Для неё нужно создавать отдельную папку  с файлом .css в папке components?

2023-06-12 04:30 UTC, Julnbul commented on index.html
> +          <ul class="preview__list">
Мне такой вариант ранее был знаком при верстке карточек. Как нужно?

2023-06-12 04:30 UTC, Julnbul commented on index.html
> +              <article class="preview-card">
Здесь не поняла. Что именно тег <a>?

2023-06-12 04:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-12 19:57 UTC, GSemikozov commented on components/main/main.css
> +.preview-card {
да, это будет отдельный компонент card

2023-06-12 19:58 UTC, GSemikozov commented on index.html
> +          <ul class="preview__list">
раньше верстали на списках чтобы правильно сгруппировать меню, в данном случае - это не список, а сетка из карточек, поэтому гораздо правильнее и проще реализовать через флекс-контейнер

2023-06-12 19:58 UTC, GSemikozov commented on index.html
> +              <article class="preview-card">
не article, а `<a>` - карточка это ссылка на страницу конкретного компонента

2023-06-15 06:37 UTC, Julnbul commented on components/main/main.css
> +.preview__list {
Сделала.

2023-06-15 06:37 UTC, Julnbul commented on components/main/main.css
> +.preview-card {
Сделала.

2023-06-15 06:38 UTC, Julnbul commented on index.html
> +          <ul class="preview__list">
Сделала.

2023-06-15 06:39 UTC, Julnbul commented on index.html
> +              <article class="preview-card">
ссылку внутри ссылки реализовала вложением внутренней ссылки в тег object. Так можно? Или есть другой более честный способ?)

2023-06-15 06:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-16 20:57 UTC, GSemikozov requested changes

2023-06-16 20:57 UTC, GSemikozov commented on components/preview-card/preview-card.css
> +.preview-card__histogram {
заранее о встраиваемых блоках ничего не знаем)
нужна общая логика в preview-card__body - например выравнивать по середине вертикально и горизонтально. А если встраиваемый блок надо ограничить по ширине например - то это уже внутренняя реализация блока, можно через модификатор

2023-06-16 20:58 UTC, GSemikozov commented on index.html
> +              <article class="preview-card">
да, в этом примере - допустимо. Но можно было просто заменить на div - превьюхи не должны быть интерактивными, это почти как просто картинка)

2023-06-17 04:12 UTC, Julnbul commented on index.html
> +              <article class="preview-card">
<a href="" class="histogram__link">View all</a> в компоненте этот элемент реализован ссылкой. Менять на див на странице превьюшек? Т.е. тут меня интересует вот какой вопрос. Правильно ли я понимаю. Отдельно компоненты создаются для того, чтобы 1.копипастить разметку 2не дублировать стили. Но если нужно поменять разметку компонента для другой страницы, то мы её меняем?

2023-06-17 04:22 UTC, Julnbul commented on components/preview-card/preview-card.css
> +.preview-card__histogram {
исправила.

2023-06-17 04:41 UTC, Julnbul commented on components/preview-card/preview-card.css
> +.preview-card__histogram {
ещё внесла изменения по цвету. ранее не заметила, что синий цвет в макете и в исходном файле main.css не совпадают и ввела новую переменную. сейчас исправила.

2023-06-17 11:04 UTC, GSemikozov commented on index.html
> +              <article class="preview-card">
в данном случае это компромиссное решение, но в мире более-менее реального проекта конечно мы так делать не будем

2023-06-17 11:06 UTC, GSemikozov requested changes

2023-06-17 11:06 UTC, GSemikozov commented on components/preview-card/preview-card.css
> +    padding: 61px 25px 0;
вообще, чтобы не задавать на уровне каждого дочернего элемента отступы - лучше задать общие на уровне блока

2023-06-17 11:06 UTC, GSemikozov commented on components/preview-card/preview-card.css
> +  margin-bottom: 32px;
и это не надо будет писать

2023-06-17 19:02 UTC, Julnbul commented on components/preview-card/preview-card.css
> +    padding: 61px 25px 0;
иногда случаются глупые ошибки) исправила

2023-06-18 10:37 UTC, GSemikozov requested changes

2023-06-18 10:37 UTC, GSemikozov commented on index.html
> +              <div class="preview-card__histogram histogram">
preview-card__histogram от этого элемента ведь избавляемся)

2023-06-18 11:08 UTC, Julnbul commented on index.html
> +              <div class="preview-card__histogram histogram">
удалила

2023-06-18 21:22 UTC, GSemikozov approved these changes

2023-06-18 21:23 UTC, merged